clear
syms alpha beta x_0 x_1 x_2 x_3

M = [
alpha, 0, 0, 0;...
0, 0, beta*exp(beta/2), - beta*exp(-beta/2);
sin(alpha*x_0) ,cos(alpha*x_0), -exp(beta*x_0), -exp(-beta*x_0);...
alpha*cos(alpha*x_0), -alpha*sin(alpha*x_0), -beta*exp(beta*x_0), beta*exp(-beta*x_0);
];

latex(M)
latex(simplify(det(M)))

M = [
1, -1, 0, 0, 0, 0;...
exp(beta*x_1), exp(-beta*x_1), -sin(alpha*x_1), -cos(alpha*x_1), 0, 0;...
beta*exp(beta*x_1), -beta*exp(-beta*x_1), -alpha*cos(alpha*x_1), alpha*sin(alpha*x_1), 0, 0;...
0, 0, sin(alpha*x_2), cos(alpha*x_2), -exp(beta*x_2), -exp(-beta*x_2);...
0, 0, alpha*cos(alpha*x_2), -alpha*sin(alpha*x_2), -beta*exp(beta*x_2), beta*exp(-beta*x_2);...
0, 0, 0, 0, exp(beta*x_3), -exp(-beta*x_3);...
];

latex(M)
latex(simplify(det(M)))