clear
syms a b x_0 x_1 x_2 x_3

M = [
a, 0, 0, 0;...
0, 0, b*exp(b/2), - b*exp(-b/2);
sin(a*x_0) ,cos(a*x_0), -exp(b*x_0), -exp(-b*x_0);...
a*cos(a*x_0), -a*sin(a*x_0), -b*exp(b*x_0), b*exp(-b*x_0);
];

latex(M)
latex(simplify(det(M)))

M = [
1, -1, 0, 0, 0, 0;...
exp(b*x_1), exp(-b*x_1), -sin(a*x_1), -cos(a*x_1), 0, 0;...
b*exp(b*x_1), -b*exp(-b*x_1), -a*cos(a*x_1), a*sin(a*x_1), 0, 0;...
0, 0, sin(a*x_2), cos(a*x_2), -exp(b*x_2), -exp(-b*x_2);...
0, 0, a*cos(a*x_2), -a*sin(a*x_2), -b*exp(b*x_2), b*exp(-b*x_2);...
0, 0, 0, 0, exp(b*x_3), -exp(-b*x_3);...
];

latex(M)
latex(simplify(det(M)))